FROM node:lts-alpine

ENV WAIT_VERSION 2.7.2
ENV HOME /usr/app

WORKDIR $HOME

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

COPY . .
RUN yarn install

CMD /wait && node hello-context.js
